name: Publish Docker Image

on:
  push:
    tags:
    - v*

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU for multi-platform builds
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push API Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: apps/api/Dockerfile
        push: true
        tags: |
          sa2avroo/sa2avroo/nginx-rtmp:latest
          sa2avroo/sa2avroo/nginx-rtmp:${{ github.sha }}
          sa2avroo/sa2avroo/nginx-rtmp:${{ github.ref_name }}

    - name: Build and push Custom SERVER API Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: apps/api/Dockerfile.server
        push: true
        tags: |
          sa2avroo/sa2avroo/nginx-rtmp-custom-server:latest
          sa2avroo/sa2avroo/nginx-rtmp-custom-server:${{ github.sha }}
          sa2avroo/sa2avroo/nginx-rtmp-custom-server:${{ github.ref_name }}

    - name: Logout from Docker Hub
      run: docker logout

      
    # - name: Check out the repo
    #   uses: actions/checkout@v3

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
    #   with:
    #     images: sa2avroo/nginx-rtmp

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}

    # - name: Build and push Docker image Custom Server
    #   uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
